name: Compile and Run C++

on:
  workflow_dispatch:
    inputs:
      dropbox_folder:
        description: 'Dropbox folder path'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Recreate Configuration.h
      run: |
        cat << 'EOF' > Configuration.h
        ${{ secrets.CONFIGURATION_H }}
        EOF
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev

    - name: show repo contents
      run: |
        pwd 
        ls -la
        
    
    - name: Compile
      run: |
        g++ -std=c++20 main.cpp -lcurl -o uploader

    - name: Run
      run: |
        ./uploader "${{ github.event.inputs.dropbox_folder }}"
